const EDITAIS = {
  'PF_AGENTE':{disciplinas:[{nome:'Português',peso:10,assuntos:['Interpretação de texto','Ortografia','Concordância','Regência','Crase','Pontuação','Redação oficial']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Conectivos','Silogismo','Sequências','Conjuntos','Porcentagem','Probabilidade']},{nome:'Direito Constitucional',peso:10,assuntos:['Princípios fundamentais','Direitos fundamentais','Segurança pública','Organização do Estado','Controle de constitucionalidade']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios LIMPE','Atos administrativos','Poderes','Agentes públicos','Licitação 14.133/21','Contratos','Responsabilidade']},{nome:'Direito Penal',peso:15,assuntos:['Teoria do crime','Crimes contra a pessoa','Crimes patrimoniais','Crimes contra administração','Crimes hediondos','Concurso de crimes']},{nome:'Direito Processual Penal',peso:15,assuntos:['Inquérito policial','Ação penal','Competência','Provas','Prisões cautelares','Habeas corpus','Recursos']},{nome:'Legislação Especial',peso:15,assuntos:['Lei de Drogas 11.343/06','Organização criminosa 12.850/13','Lavagem de dinheiro 9.613/98','Abuso de autoridade 13.869/19','ECA','Maria da Penha','Estatuto do Desarmamento']},{nome:'Informática',peso:5,assuntos:['Windows','Office','Internet e segurança','Redes','Criptografia']},{nome:'Língua Inglesa',peso:5,assuntos:['Interpretação em inglês','Vocabulário','Gramática básica']},{nome:'Inteligência Policial',peso:5,assuntos:['Atividade de inteligência','Ciclo do conhecimento','Contra-inteligência']}]},
  'PF_DELEGADO':{disciplinas:[{nome:'Direito Penal',peso:20,assuntos:['Teoria geral do crime','Crimes em espécie CP','Lei de Drogas','Organização criminosa','Crimes ambientais','Crimes de informática']},{nome:'Direito Processual Penal',peso:20,assuntos:['Princípios processuais','Inquérito policial','Ação penal','Provas','Prisões','Nulidades','Recursos','Pacote anticrime']},{nome:'Medicina Legal',peso:10,assuntos:['Tanatologia','Traumatologia','Sexologia forense','Toxicologia','DNA forense']},{nome:'Criminalística',peso:10,assuntos:['Local do crime','Documentoscopia','Balística forense','Cadeia de custódia']},{nome:'Direito Constitucional',peso:10,assuntos:['Teoria da Constituição','Direitos fundamentais','Controle de constitucionalidade']},{nome:'Direito Administrativo',peso:10,assuntos:['Administração pública','Atos administrativos','Agentes públicos','Licitação']},{nome:'Legislação Especial',peso:10,assuntos:['ECA','Maria da Penha','Abuso de autoridade','Lavagem de dinheiro']},{nome:'Direito Civil',peso:5,assuntos:['Pessoas','Bens','Negócio jurídico','Prescrição']},{nome:'Português',peso:5,assuntos:['Interpretação de texto','Redação jurídica']}]},
  'PRF':{disciplinas:[{nome:'Português',peso:10,assuntos:['Interpretação de texto','Ortografia','Concordância','Redação oficial']},{nome:'Raciocínio Lógico e Matemática',peso:15,assuntos:['Lógica','Porcentagem','Juros','Progressões','Estatística','Geometria']},{nome:'Direito Constitucional',peso:10,assuntos:['Princípios fundamentais','Direitos fundamentais','Segurança pública']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Atos administrativos','Agentes públicos','Licitação']},{nome:'Legislação de Trânsito',peso:25,assuntos:['CTB completo','Habilitação','Infrações e penalidades','Crimes de trânsito','Fiscalização','Sinalização']},{nome:'Direito Penal e Processual',peso:15,assuntos:['Teoria do crime','Crimes de trânsito','Drogas','Inquérito policial','Prisões']},{nome:'Legislação Especial',peso:10,assuntos:['Estatuto do Desarmamento','Lei de Drogas','Abuso de autoridade']},{nome:'Primeiros Socorros',peso:5,assuntos:['RCP','Hemorragias','Politraumatizado','Transporte de acidentados']}]},
  'INSS_TECNICO':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação de texto','Ortografia','Concordância','Regência','Crase','Pontuação','Redação oficial']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Conectivos','Silogismo','Sequências','Porcentagem','Juros','Regra de três']},{nome:'Direito Constitucional',peso:10,assuntos:['Princípios fundamentais','Direitos sociais','Seguridade social na CF','Ordem social']},{nome:'Direito Administrativo',peso:15,assuntos:['Princípios LIMPE','Atos administrativos','Agentes públicos','Lei 8.112/90','Licitação 14.133/21','Contratos','Responsabilidade','Improbidade','Processo administrativo 9.784/99']},{nome:'Direito Previdenciário',peso:25,assuntos:['Seguridade social','RGPS custeio Lei 8.212/91','RGPS benefícios Lei 8.213/91','Aposentadorias','Auxílios','Salário-maternidade','Pensão por morte','BPC/LOAS','Decadência e prescrição']},{nome:'Legislação Previdenciária',peso:15,assuntos:['Lei 8.212/91','Lei 8.213/91','Decreto 3.048/99','EC 103/2019','IN INSS 128/2022']},{nome:'Informática',peso:10,assuntos:['Windows','Word','Excel','Internet e segurança','Redes','LGPD']}]},
  'INSS_ANALISTA':{disciplinas:[{nome:'Português',peso:10,assuntos:['Interpretação','Redação oficial','Gramática avançada']},{nome:'Direito Constitucional',peso:10,assuntos:['Teoria da Constituição','Direitos fundamentais','Seguridade social','Controle de constitucionalidade']},{nome:'Direito Administrativo',peso:15,assuntos:['Princípios','Organização administrativa','Atos administrativos','Agentes públicos','Licitação','Contratos','Controle','Improbidade']},{nome:'Direito Previdenciário',peso:25,assuntos:['Seguridade social','Lei 8.212/91','Lei 8.213/91','Decreto 3.048/99','EC 103/2019','Jurisprudência STJ/TNU']},{nome:'Direito do Trabalho',peso:10,assuntos:['Relação de emprego','Contrato de trabalho','Jornada','Remuneração','Rescisão','FGTS']},{nome:'Raciocínio Lógico e Estatística',peso:10,assuntos:['Lógica','Estatística descritiva','Probabilidade']},{nome:'Administração Pública',peso:10,assuntos:['Gestão pública','Planejamento estratégico','Gestão de processos','Governança']},{nome:'Informática',peso:10,assuntos:['Office avançado','Sistemas de informação','LGPD','Segurança']}]},
  'RECEITA_AUDITOR':{disciplinas:[{nome:'Direito Tributário',peso:25,assuntos:['Sistema Tributário Nacional','CTN completo','Princípios tributários','IR PF e PJ','IPI','IOF','PIS/COFINS','CSLL','Simples Nacional','Processo administrativo fiscal']},{nome:'Direito Aduaneiro',peso:15,assuntos:['Controle aduaneiro','Despacho de importação','Despacho de exportação','Valor aduaneiro','TEC','Drawback']},{nome:'Contabilidade Geral e Avançada',peso:20,assuntos:['Demonstrações financeiras','Análise de balanço','IFRS e CPC','Lucro Real LALUR','Lucro Presumido','Consolidação']},{nome:'Direito Constitucional',peso:10,assuntos:['Sistema tributário na CF','Imunidades','Direitos fundamentais']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Processo administrativo','Licitação','Agentes públicos']},{nome:'Raciocínio Lógico e Estatística',peso:10,assuntos:['Lógica','Estatística','Probabilidade','Análise quantitativa']},{nome:'Tecnologia da Informação',peso:5,assuntos:['SPED','NF-e','EFD','Segurança da informação','LGPD']},{nome:'Português',peso:5,assuntos:['Interpretação','Redação oficial']}]},
  'TCU_ANALISTA':{disciplinas:[{nome:'Direito Constitucional',peso:15,assuntos:['TCU na CF arts 70-75','Controle externo','Fiscalização financeira','Organização do Estado']},{nome:'Direito Administrativo',peso:20,assuntos:['Princípios','Administração pública','Licitação 14.133/21','Contratos','Agentes públicos','Controle','Tomada de contas']},{nome:'Controle Externo e Auditoria',peso:20,assuntos:['Lei Orgânica TCU 8.443/92','Auditoria governamental','NBC TA','Riscos','Relatório de auditoria','COSO e COBIT']},{nome:'Contabilidade Pública',peso:15,assuntos:['MCASP','Orçamento público PPA LDO LOA','SIAFI','Execução orçamentária','Dívida pública']},{nome:'Administração Pública',peso:10,assuntos:['Planejamento estratégico','Gestão de processos','Governança pública','Gestão de riscos']},{nome:'Direito Financeiro',peso:5,assuntos:['Lei 4.320/64','LRF 101/2000','Orçamento público']},{nome:'Português',peso:10,assuntos:['Interpretação','Redação','Gramática']},{nome:'Raciocínio Lógico',peso:5,assuntos:['Lógica','Estatística','Análise de dados']}]},
  'BB_ESCRITURARIO':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação de texto','Ortografia','Concordância','Regência','Pontuação','Redação']},{nome:'Matemática e Raciocínio Lógico',peso:20,assuntos:['Porcentagem','Juros simples e compostos','Amortização SAC e PRICE','Desconto bancário','Probabilidade','Estatística','Lógica proposicional']},{nome:'Atualidades do Mercado Financeiro',peso:15,assuntos:['SFN','BACEN','CMN','CVM','Produtos bancários','Crédito e garantias','Compliance','LGPD','Open banking','PIX']},{nome:'Conhecimentos Bancários',peso:20,assuntos:['Operações ativas e passivas','CDB e poupança','Fundos de investimento','Previdência privada','Seguros','Câmbio','Mercado de capitais','Crédito imobiliário']},{nome:'Legislação e Ética',peso:10,assuntos:['CDC','Crimes contra o SFN','Lavagem de dinheiro','LGPD','Sigilo bancário','Ética bancária']},{nome:'Tecnologia e Inovação',peso:10,assuntos:['Open banking','Fintechs','Blockchain','Cibersegurança','Transformação digital']},{nome:'Vendas e Negociação',peso:10,assuntos:['Técnicas de vendas','CRM','Negociação','Marketing bancário','NPS']}]},
  'CEF_TECNICO':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação de texto','Gramática','Redação']},{nome:'Matemática Financeira',peso:20,assuntos:['Porcentagem','Juros simples e compostos','SAC e PRICE','VP e VF','Desconto bancário']},{nome:'Conhecimentos Bancários e Habitacionais',peso:20,assuntos:['SFN e SFH','SFI','FGTS habitacional','Produtos CEF','Poupança','Fundos','Previdência','Seguros']},{nome:'Vendas e Atendimento',peso:15,assuntos:['Técnicas de vendas','Marketing','CRM','Negociação']},{nome:'Legislação',peso:15,assuntos:['LGPD','CDC','Lavagem de dinheiro','Compliance','Prevenção a fraudes']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Lógica','Sequências','Probabilidade','Estatística']},{nome:'Informática',peso:5,assuntos:['Office','Internet','Segurança','Open banking']}]},
  'TJ_ANALISTA':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação de texto','Redação oficial','Gramática','Coesão']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Silogismo','Sequências','Probabilidade']},{nome:'Direito Constitucional',peso:20,assuntos:['Princípios fundamentais','Direitos fundamentais','Poder Judiciário','MP','Controle de constitucionalidade']},{nome:'Direito Administrativo',peso:20,assuntos:['Princípios LIMPE','Atos administrativos','Agentes públicos','Licitação 14.133/21','Contratos','Responsabilidade','Improbidade']},{nome:'Direito Civil',peso:15,assuntos:['LINDB','Pessoas','Bens','Negócio jurídico','Contratos','Responsabilidade civil','Família','Sucessões']},{nome:'Direito Processual Civil',peso:15,assuntos:['CPC/2015','Competência','Tutelas provisórias','Provas','Sentença','Recursos','Execução']},{nome:'Informática',peso:5,assuntos:['Windows','Office','PJe','LGPD']}]},
  'TJ_TECNICO':{disciplinas:[{nome:'Português',peso:20,assuntos:['Interpretação','Ortografia','Concordância','Regência','Crase','Redação oficial']},{nome:'Raciocínio Lógico',peso:15,assuntos:['Proposições','Silogismo','Sequências','Conjuntos','Porcentagem']},{nome:'Direito Constitucional',peso:20,assuntos:['Princípios fundamentais','Direitos fundamentais','Poder Judiciário','Garantias processuais']},{nome:'Direito Administrativo',peso:20,assuntos:['Princípios','Atos administrativos','Agentes públicos','Licitação','Responsabilidade']},{nome:'Noções de Processo Civil',peso:15,assuntos:['Atos processuais','Petição inicial','Prazos','Recursos','PJe']},{nome:'Informática',peso:10,assuntos:['Windows','Word','Excel','Internet','Segurança','PJe']}]},
  'PC_INVESTIGADOR':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação de texto','Ortografia','Concordância','Regência','Crase','Pontuação','Redação oficial']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Conectivos','Silogismo','Sequências','Conjuntos','Porcentagem','Probabilidade']},{nome:'Direito Constitucional',peso:15,assuntos:['Princípios fundamentais','Direitos fundamentais','Segurança pública','Organização do Estado','Controle de constitucionalidade']},{nome:'Direito Penal',peso:20,assuntos:['Teoria do crime','Crimes contra a vida','Lesão corporal','Crimes patrimoniais','Crimes contra administração','Crimes hediondos','Concurso de crimes']},{nome:'Direito Processual Penal',peso:15,assuntos:['Inquérito policial','Ação penal','Competência','Provas','Prisão em flagrante','Prisão preventiva','Prisão temporária','Habeas corpus']},{nome:'Legislação Especial',peso:10,assuntos:['Lei de Drogas 11.343/06','Organização criminosa 12.850/13','Abuso de autoridade 13.869/19','ECA 8.069/90','Maria da Penha 11.340/06','Estatuto do Desarmamento']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Atos administrativos','Agentes públicos','Licitação','Responsabilidade']},{nome:'Informática',peso:5,assuntos:['Windows','Office','Internet','Segurança digital']}]},
  'PC_DELEGADO':{disciplinas:[{nome:'Direito Penal',peso:20,assuntos:['Teoria geral do crime','Extinção da punibilidade','Crimes em espécie CP','Lei de Drogas','Organização criminosa','Crimes ambientais']},{nome:'Direito Processual Penal',peso:20,assuntos:['Princípios processuais','Inquérito policial','Ação penal','Provas','Prisões cautelares','Nulidades','Pacote anticrime']},{nome:'Medicina Legal',peso:10,assuntos:['Tanatologia','Traumatologia','Sexologia forense','Toxicologia','DNA forense']},{nome:'Criminalística',peso:10,assuntos:['Local do crime','Documentoscopia','Balística','Cadeia de custódia']},{nome:'Direito Constitucional',peso:10,assuntos:['Teoria da Constituição','Direitos fundamentais','Hermenêutica']},{nome:'Direito Administrativo',peso:10,assuntos:['Administração pública','Atos administrativos','Agentes públicos','Controle']},{nome:'Legislação Especial',peso:10,assuntos:['ECA','Maria da Penha','Abuso de autoridade','Lavagem de dinheiro']},{nome:'Português',peso:5,assuntos:['Interpretação','Redação jurídica']},{nome:'Direito Civil',peso:5,assuntos:['Pessoas','Negócio jurídico','Prescrição']}]},
  'PM_SOLDADO':{disciplinas:[{nome:'Português',peso:20,assuntos:['Interpretação de texto','Ortografia','Concordância','Regência','Crase','Pontuação']},{nome:'Matemática',peso:15,assuntos:['Operações','Porcentagem','Razão e proporção','Regra de três','Juros simples','Geometria']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Conectivos','Silogismo','Sequências','Conjuntos']},{nome:'Direito Constitucional',peso:15,assuntos:['Princípios fundamentais','Direitos fundamentais','Segurança pública']},{nome:'Direito Penal e Processual',peso:15,assuntos:['Teoria do crime','Crimes contra a pessoa','Crimes patrimoniais','Lei de Drogas','Prisões']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Atos administrativos','Agentes públicos','Responsabilidade']},{nome:'Conhecimentos Gerais',peso:10,assuntos:['Atualidades','História do Brasil','Geografia','Direitos Humanos']},{nome:'Primeiros Socorros',peso:5,assuntos:['RCP','Hemorragias','Fraturas','Transporte de acidentados']}]},
  'SEFAZ_AUDITOR':{disciplinas:[{nome:'Direito Tributário',peso:25,assuntos:['Sistema Tributário Nacional','CTN completo','Princípios tributários','ICMS','ISS','IPVA','ITCMD','Simples Nacional','Processo administrativo tributário']},{nome:'Direito Constitucional',peso:10,assuntos:['Sistema tributário na CF','Repartição de receitas','Direitos fundamentais']},{nome:'Direito Administrativo',peso:15,assuntos:['Princípios','Atos administrativos','Agentes públicos','Licitação','Controle']},{nome:'Contabilidade Geral e Fiscal',peso:20,assuntos:['Demonstrações financeiras','SPED','NF-e','EFD-ICMS','Recuperação de créditos fiscais']},{nome:'Auditoria Fiscal',peso:15,assuntos:['Técnicas de auditoria','Planejamento','Sonegação fiscal','Crimes tributários','Fraudes contábeis']},{nome:'Raciocínio Lógico',peso:5,assuntos:['Lógica','Estatística','Análise de dados']},{nome:'Informática',peso:5,assuntos:['Excel avançado','SPED na prática','Sistemas tributários']},{nome:'Português',peso:5,assuntos:['Interpretação','Redação oficial']}]},
  'PROFESSOR_ESTADUAL':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação de texto','Gramática','Redação']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Sequências','Conjuntos','Porcentagem']},{nome:'Direito Constitucional',peso:10,assuntos:['Direitos fundamentais','Direito à educação','Organização do Estado']},{nome:'Conhecimentos Pedagógicos',peso:20,assuntos:['Didática','Planejamento de ensino','Avaliação','Teorias da aprendizagem','BNCC','Educação inclusiva']},{nome:'Legislação Educacional',peso:15,assuntos:['LDB 9.394/96','BNCC','Estatuto do Magistério','PNE','ECA — educação']},{nome:'Conhecimentos Específicos',peso:20,assuntos:['Fundamentos da disciplina','Metodologia de ensino','Histórico da área','Interdisciplinaridade']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Agentes públicos','Responsabilidade']}]},
  'EBSERH_ENFERMEIRO':{disciplinas:[{nome:'Português',peso:10,assuntos:['Interpretação','Redação oficial']},{nome:'Legislação em Saúde',peso:15,assuntos:['SUS — princípios','Lei 8.080/90','Lei 8.142/90','COFEN — ética','Lei exercício profissional 7.498/86']},{nome:'Saúde Coletiva',peso:15,assuntos:['Vigilância epidemiológica','Indicadores de saúde','Doenças de notificação','ESF e PNAB']},{nome:'Enfermagem Médico-Cirúrgica',peso:20,assuntos:['Semiologia','Sinais vitais','Administração de medicamentos','Curativos','Cateterismo','Sondagem','Oxigenoterapia']},{nome:'Urgência e Emergência',peso:15,assuntos:['RCP avançado','Politraumatismo','Choque','Queimaduras','Triagem de Manchester']},{nome:'Saúde Mental',peso:10,assuntos:['Reforma psiquiátrica','CAPS','Transtornos mentais','Lei 10.216/01']},{nome:'Gestão em Enfermagem',peso:10,assuntos:['SAE','CIPE','Indicadores de qualidade','Gestão de resíduos']},{nome:'Direito Administrativo',peso:5,assuntos:['Princípios','Agentes públicos','Contratos']}]},
  'PREFEITURA_ANALISTA':{disciplinas:[{nome:'Português',peso:20,assuntos:['Interpretação','Ortografia','Concordância','Regência','Crase','Redação oficial']},{nome:'Raciocínio Lógico',peso:15,assuntos:['Proposições','Silogismo','Sequências','Porcentagem','Probabilidade']},{nome:'Direito Constitucional',peso:15,assuntos:['Princípios fundamentais','Direitos fundamentais','Municípios na CF']},{nome:'Direito Administrativo',peso:20,assuntos:['Princípios','Atos administrativos','Agentes públicos','Licitação 14.133/21','Contratos','Responsabilidade','Improbidade']},{nome:'Direito Municipal',peso:10,assuntos:['Lei Orgânica Municipal','Tributos municipais','LRF','Estatuto das Cidades']},{nome:'Informática',peso:10,assuntos:['Windows','Office','Internet','Sistemas municipais']},{nome:'Conhecimentos Específicos',peso:10,assuntos:['Legislação da área','Ética profissional','Técnicas da profissão']}]},
  'AGU_ADVOGADO':{disciplinas:[{nome:'Direito Constitucional',peso:15,assuntos:['Teoria da Constituição','Direitos fundamentais','Controle de constitucionalidade','ADI e ADPF']},{nome:'Direito Administrativo',peso:20,assuntos:['Princípios','Organização administrativa','Atos administrativos','Licitação 14.133/21','Contratos','PPP','Responsabilidade','Improbidade']},{nome:'Direito Civil',peso:15,assuntos:['LINDB','Pessoas','Bens','Negócio jurídico','Contratos','Responsabilidade civil','Família','Sucessões']},{nome:'Direito Processual Civil',peso:15,assuntos:['CPC completo','Tutelas provisórias','Recursos','Execução','Ação popular','ACP','Mandado de segurança']},{nome:'Direito Tributário',peso:10,assuntos:['Sistema tributário','CTN','Tributos federais','Execução fiscal','Imunidades']},{nome:'Direito Financeiro',peso:5,assuntos:['LRF','Lei 4.320/64','Orçamento público']},{nome:'Direito Internacional',peso:5,assuntos:['Tratados','ONU','Direitos humanos internacionais','MERCOSUL']},{nome:'Português',peso:5,assuntos:['Interpretação','Redação jurídica']},{nome:'Raciocínio Lógico',peso:5,assuntos:['Lógica','Argumentação jurídica']},{nome:'Direito Empresarial',peso:5,assuntos:['Sociedades','Falência','Títulos de crédito']}]},
  'BNB_ANALISTA':{disciplinas:[{nome:'Português',peso:10,assuntos:['Interpretação','Redação','Gramática']},{nome:'Matemática e Raciocínio Lógico',peso:15,assuntos:['Porcentagem','Juros','Amortização','Probabilidade','Estatística','Lógica']},{nome:'Conhecimentos Bancários',peso:20,assuntos:['SFN','BACEN','Produtos bancários','Crédito','Câmbio','Mercado de capitais']},{nome:'Desenvolvimento Regional',peso:15,assuntos:['Região Nordeste','FNE','Pronaf','Microcrédito','Semiárido','Desenvolvimento sustentável']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Atos administrativos','Licitação','Agentes públicos']},{nome:'Atualidades e Economia',peso:10,assuntos:['Macroeconomia','Indicadores econômicos','Mercado de trabalho','Política monetária']},{nome:'Contabilidade Geral',peso:10,assuntos:['Demonstrações financeiras','Análise de balanço','Custos']},{nome:'Legislação',peso:10,assuntos:['LGPD','Lavagem de dinheiro','CDC','Compliance']}]},
  'GENERICO_POLICIAL':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação','Ortografia','Concordância','Redação']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Silogismo','Sequências','Porcentagem']},{nome:'Direito Constitucional',peso:15,assuntos:['Princípios fundamentais','Direitos fundamentais','Segurança pública']},{nome:'Direito Penal',peso:20,assuntos:['Teoria do crime','Crimes contra a pessoa','Crimes patrimoniais','Lei de Drogas']},{nome:'Direito Processual Penal',peso:15,assuntos:['Inquérito policial','Ação penal','Provas','Prisões','Habeas corpus']},{nome:'Legislação Especial',peso:10,assuntos:['ECA','Maria da Penha','Abuso de autoridade','Organização criminosa']},{nome:'Direito Administrativo',peso:10,assuntos:['Princípios','Atos administrativos','Agentes públicos']},{nome:'Informática',peso:5,assuntos:['Windows','Office','Internet']}]},
  'GENERICO_JUDICIAL':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação','Redação oficial','Gramática']},{nome:'Raciocínio Lógico',peso:10,assuntos:['Proposições','Silogismo','Sequências','Probabilidade']},{nome:'Direito Constitucional',peso:20,assuntos:['Princípios fundamentais','Direitos fundamentais','Poder Judiciário','Controle de constitucionalidade']},{nome:'Direito Administrativo',peso:20,assuntos:['Princípios','Atos administrativos','Agentes públicos','Licitação','Responsabilidade','Improbidade']},{nome:'Direito Civil',peso:15,assuntos:['LINDB','Pessoas','Bens','Negócio jurídico','Contratos','Responsabilidade civil']},{nome:'Direito Processual Civil',peso:15,assuntos:['CPC/2015','Competência','Provas','Sentença','Recursos','Execução']},{nome:'Informática',peso:5,assuntos:['Windows','Office','PJe','LGPD']}]},
  'GENERICO_ADMINISTRATIVA':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação','Ortografia','Concordância','Regência','Redação oficial']},{nome:'Raciocínio Lógico',peso:15,assuntos:['Proposições','Silogismo','Sequências','Porcentagem','Probabilidade']},{nome:'Direito Constitucional',peso:15,assuntos:['Princípios fundamentais','Direitos fundamentais','Organização do Estado']},{nome:'Direito Administrativo',peso:25,assuntos:['Princípios LIMPE','Organização administrativa','Atos administrativos','Agentes públicos','Licitação 14.133/21','Contratos','Responsabilidade','Improbidade']},{nome:'Informática',peso:15,assuntos:['Windows','Word','Excel','Internet','LGPD']},{nome:'Administração Geral',peso:10,assuntos:['Funções administrativas','Planejamento','Gestão de processos','Atendimento ao cidadão']},{nome:'Conhecimentos Específicos',peso:5,assuntos:['Legislação do órgão','Ética no serviço público']}]},
  'GENERICO_BANCARIA':{disciplinas:[{nome:'Português',peso:15,assuntos:['Interpretação','Gramática','Redação']},{nome:'Matemática e Raciocínio Lógico',peso:20,assuntos:['Porcentagem','Juros','Amortização','Probabilidade','Estatística','Lógica']},{nome:'Atualidades do Mercado Financeiro',peso:15,assuntos:['SFN','BACEN','CMN','Produtos bancários','Compliance','LGPD']},{nome:'Conhecimentos Bancários',peso:20,assuntos:['Operações bancárias','Fundos','Previdência','Seguros','Câmbio','Mercado de capitais','PIX']},{nome:'Legislação',peso:10,assuntos:['CDC','Lavagem de dinheiro','LGPD','Sigilo bancário']},{nome:'Vendas e Atendimento',peso:10,assuntos:['Técnicas de vendas','CRM','Negociação']},{nome:'Informática',peso:10,assuntos:['Office','Internet','Segurança bancária']}]}
};

const MAPA = [
  {k:['POLÍCIA FEDERAL','PF —','PF-'],c:{DELEGADO:'PF_DELEGADO'},d:'PF_AGENTE'},
  {k:['PRF','RODOVIÁRIA FEDERAL'],d:'PRF'},
  {k:['PCDF','POLÍCIA CIVIL DO DF','POLÍCIA CIVIL DF'],c:{DELEGADO:'PC_DELEGADO'},d:'PC_INVESTIGADOR'},
  {k:['PC-BA','POLÍCIA CIVIL DA BAHIA','POLÍCIA CIVIL BAHIA'],c:{DELEGADO:'PC_DELEGADO',ESCRIVÃO:'PC_INVESTIGADOR',ESCRIVAO:'PC_INVESTIGADOR'},d:'PC_INVESTIGADOR'},
  {k:['PC-SP','POLÍCIA CIVIL DE SÃO PAULO','POLÍCIA CIVIL SP'],c:{DELEGADO:'PC_DELEGADO'},d:'PC_INVESTIGADOR'},
  {k:['PC-RJ','POLÍCIA CIVIL DO RIO','POLÍCIA CIVIL RJ'],c:{DELEGADO:'PC_DELEGADO'},d:'PC_INVESTIGADOR'},
  {k:['PC-MG','POLÍCIA CIVIL DE MINAS','POLÍCIA CIVIL MG'],c:{DELEGADO:'PC_DELEGADO'},d:'PC_INVESTIGADOR'},
  {k:['POLÍCIA CIVIL','PC-','PC —'],c:{DELEGADO:'PC_DELEGADO'},d:'PC_INVESTIGADOR'},
  {k:['PM-','PM —','POLÍCIA MILITAR','BM-','BOMBEIRO'],d:'PM_SOLDADO'},
  {k:['INSS'],c:{ANALISTA:'INSS_ANALISTA',TÉCNICO:'INSS_TECNICO',TECNICO:'INSS_TECNICO'},d:'INSS_TECNICO'},
  {k:['RECEITA FEDERAL'],d:'RECEITA_AUDITOR'},
  {k:['TCU'],d:'TCU_ANALISTA'},
  {k:['AGU','ADVOCACIA-GERAL'],d:'AGU_ADVOGADO'},
  {k:['BANCO DO BRASIL','BB —','BB-'],d:'BB_ESCRITURARIO'},
  {k:['CEF','CAIXA ECONÔMICA','CAIXA ECONOMICA'],d:'CEF_TECNICO'},
  {k:['BNB','BANCO DO NORDESTE'],d:'BNB_ANALISTA'},
  {k:['TRF'],c:{TÉCNICO:'TJ_TECNICO',TECNICO:'TJ_TECNICO'},d:'TJ_ANALISTA'},
  {k:['TJ —','TJ-','TRIBUNAL DE JUSTIÇA','TRIBUNAL DE JUSTICA'],c:{TÉCNICO:'TJ_TECNICO',TECNICO:'TJ_TECNICO',ESCREVENTE:'TJ_TECNICO'},d:'TJ_ANALISTA'},
  {k:['TST','TSE','STJ','STF'],d:'TJ_ANALISTA'},
  {k:['SEFAZ','SECRETARIA DA FAZENDA'],d:'SEFAZ_AUDITOR'},
  {k:['PROFESSOR','SEE-','SEC-','MAGISTÉRIO','MAGISTERIO'],d:'PROFESSOR_ESTADUAL'},
  {k:['EBSERH','HOSPITAL UNIVERSITÁRIO','HOSPITAL UNIVERSITARIO'],d:'EBSERH_ENFERMEIRO'},
  {k:['PREFEITURA','CÂMARA MUNICIPAL','CAMARA MUNICIPAL'],d:'PREFEITURA_ANALISTA'},
];

function norm(s){return(s||'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}

function identificarEdital(concurso){
  const u=norm(concurso);
  for(const m of MAPA){
    if(m.k.some(k=>u.includes(norm(k)))){
      if(m.c){
        for(const[ck,ek]of Object.entries(m.c)){
          if(u.includes(norm(ck)))return EDITAIS[ek]||null;
        }
      }
      return EDITAIS[m.d]||null;
    }
  }
  return null;
}

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type');
  if(req.method==='OPTIONS')return res.status(200).end();

  try{
    let body=req.body;
    if(typeof body==='string')body=JSON.parse(body);
    if(!body)body={};

    const{concurso,nivel,horas_dia,data_prova,desempenho,area}=body;

    let edital=identificarEdital(concurso);
    if(!edital){
      const FB={policial:EDITAIS.GENERICO_POLICIAL,judicial:EDITAIS.GENERICO_JUDICIAL,administrativa:EDITAIS.GENERICO_ADMINISTRATIVA,bancaria:EDITAIS.GENERICO_BANCARIA,saude:EDITAIS.EBSERH_ENFERMEIRO,educacao:EDITAIS.PROFESSOR_ESTADUAL};
      edital=FB[area]||EDITAIS.GENERICO_ADMINISTRATIVA;
    }

    let numSemanas=4;
    if(data_prova){
      const dias=Math.ceil((new Date(data_prova+'T00:00:00')-new Date())/(864e5));
      if(dias>0)numSemanas=Math.min(Math.max(Math.ceil(dias/7),4),6);
    }

    const desempStr=desempenho&&Object.keys(desempenho).length
      ?Object.entries(desempenho).map(([d,v])=>`${d}:${Math.round(v.acertos/v.total*100)}%`).join(',')
      :'sem histórico';

    // Lista compacta: só nome e peso
    const discList=edital.disciplinas
      .sort((a,b)=>b.peso-a.peso)
      .map(d=>d.nome+'('+d.peso+'%)')
      .join(', ');

    const prompt='Crie plano de estudos JSON para: concurso="'+concurso+'", nivel='+
      (nivel||'intermediario')+', '+
      (horas_dia||'2h')+'/dia, '+numSemanas+' semanas, desempenho={'+desempStr+'}.'+
      ' Disciplinas do edital: '+discList+'.'+
      ' REGRAS: 2 disciplinas por semana maximo, 2 assuntos por disciplina maximo, ultima semana e revisao.'+
      ' RESPONDA APENAS JSON: {"semanas":[{"numero":1,"titulo":"string","foco":"string","tipo":"introducao","disciplinas":[{"nome":"string","peso":15,"prioridade":"alta","meta_questoes":20,"horas_semana":4,"assuntos":["assunto1","assunto2"]}]}],"dica_ia":"string","resumo":"string","total_semanas":'+numSemanas+',"total_horas":0,"disciplinas_criticas":[],"disciplinas_ok":[]}';

    const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{
      method:'POST',
      headers:{'Content-Type':'application/json','Authorization':'Bearer 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'},
      body:JSON.stringify({
        model:'llama-3.3-70b-versatile',
        messages:[
          {role:'system',content:'Responda APENAS JSON puro valido, sem markdown, sem texto adicional.'},
          {role:'user',content:prompt}
        ],
        temperature:0.2,
        max_tokens:1500
      })
    });

    const raw=await r.json();
    if(raw.error)throw new Error('Groq: '+JSON.stringify(raw.error));
    if(!raw.choices?.[0]?.message?.content)throw new Error('Sem resposta Groq');

    let txt=raw.choices[0].message.content.replace(/```json|```/g,'').trim();
    const ji=txt.indexOf('{');
    if(ji>0)txt=txt.substring(ji);
    // Remove any trailing text after last }
    const jEnd=txt.lastIndexOf('}');
    if(jEnd>=0)txt=txt.substring(0,jEnd+1);

    let plano;
    try{plano=JSON.parse(txt);}
    catch(e){throw new Error('JSON invalido: '+e.message+' len:'+txt.length);}

    plano._edital=edital;
    return res.status(200).json(plano);

  }catch(err){
    console.error(err.message);
    return res.status(500).json({error:err.message});
  }
}
